-- Insert all retailers from CSV (handles all 367 rows)
-- This uses ON CONFLICT to skip duplicates if you run it multiple times

INSERT INTO retailers (name, link, wholesale, cancel_for_bulk, location, shopify, total_spend, total_qty_of_items_ordered, percent_of_cancelled_qty)
SELECT 
    TRIM(name_col) as name,
    NULLIF(TRIM(link_col), '') as link,
    COALESCE(NULLIF(TRIM(wholesale_col), ''), 'n/a') as wholesale,
    CASE WHEN LOWER(TRIM(cancel_col)) = 'yes' THEN true ELSE false END as cancel_for_bulk,
    NULLIF(TRIM(location_col), '') as location,
    CASE WHEN LOWER(TRIM(shopify_col)) = 'yes' THEN true ELSE false END as shopify,
    COALESCE(
        CAST(
            NULLIF(
                REGEXP_REPLACE(TRIM(spend_col), '[^0-9.]', '', 'g'),
                ''
            ) AS NUMERIC
        ),
        0
    ) as total_spend,
    COALESCE(
        CAST(
            NULLIF(
                REGEXP_REPLACE(TRIM(qty_col), '[^0-9]', '', 'g'),
                ''
            ) AS INTEGER
        ),
        0
    ) as total_qty_of_items_ordered,
    COALESCE(
        CAST(
            NULLIF(
                REGEXP_REPLACE(TRIM(percent_col), '[^0-9.]', '', 'g'),
                ''
            ) AS NUMERIC
        ),
        0
    ) as percent_of_cancelled_qty
FROM (
    VALUES
        ('n/a', 'No', 'USA', 'No', '$275,200.96', '7616', '0.00%', 'Blue Time Inc', '', ''),
        ('No', 'No', 'USA', 'No', '$228,132.90', '3016', '10.34%', 'Foot Locker', 'https://www.footlocker.com/', '11'),
        ('No', 'No', 'USA', 'No', '$133,298.57', '2928', '42.83%', 'Finish Line', 'https://www.finishline.com/', '3'),
        ('No', 'No', 'USA', 'No', '$80,789.31', '1008', '14.65%', 'Nike', 'https://www.nike.com/', '1'),
        ('No', 'No', 'USA', 'No', '$66,826.99', '1014', '2.78%', 'Snipes', 'https://www.snipesusa.com/', '5'),
        ('n/a', 'No', 'USA', 'Yes', '$52,787.58', '614', '0.81%', 'Orleans Shoe Co.', 'https://orleansshoes.com/', '0'),
        ('No', 'No', 'USA', 'No', '$66,262.07', '1086', '8.35%', 'Champs Sports', 'https://www.champssports.com/', '4'),
        ('No', 'No', 'EU', 'No', '$37,008.20', '703', '0.71%', 'ASOS', 'https://www.asos.com/', '0'),
        ('No', 'No', 'USA', 'Yes', '$39,619.18', '712', '22.86%', 'DTLR', 'https://www.dtlr.com/', '1'),
        ('No', 'No', 'USA', 'No', '$26,222.72', '645', '0.00%', 'Converse', 'https://www.converse.com/', '5'),
        ('n/a', 'Yes', 'USA', 'No', '$20,969.30', '271', '23.66%', 'Shopbop', 'https://www.shopbop.com/', '1'),
        ('n/a', 'Yes', 'EU', 'No', '$19,626.77', '181', '35.82%', 'Net a Porter', 'https://www.net-a-porter.com', '0'),
        ('No', 'No', 'USA', 'No', '$19,247.23', '218', '5.22%', 'Revolve', 'https://www.revolve.com/', '0'),
        ('No', 'Yes', 'USA', 'Yes', '$17,700.83', '459', '0.86%', 'Feature', 'https://feature.com/', '0'),
        ('No', 'No', 'USA', 'Yes', '$13,822.84', '300', '7.12%', 'Bandier', 'https://www.bandier.com/', '4'),
        ('No', 'No', 'USA', 'Yes', '$13,790.94', '182', '1.62%', 'Concepts', 'https://cncpts.com/', '0'),
        ('No', 'No', 'USA', 'Yes', '$11,276.72', '173', '3.89%', 'Likelihood', 'https://likelihood.us/', '1'),
        ('No', 'N/A', 'USA', 'No', '$48,164.40', '1004', '26.12%', 'Hibbett', 'https://www.hibbett.com/', '6'),
        ('n/a', 'No', 'USA', 'No', '$13,559.20', '552', '2.47%', 'Adidas', '', '4'),
        ('No', 'No', 'EU', 'No', '$14,258.24', '259', '0.38%', 'END Clothing', 'https://www.endclothing.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$9,455.76', '128', '0.78%', 'Sneaker Politics', 'https://sneakerpolitics.com/', '1'),
        ('Yes', 'No', 'USA', 'No', '$8,680.00', '100', '0.00%', 'BSN Sports', 'https://www.bsnsports.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$8,671.60', '91', '1.09%', 'FWRD', 'https://www.fwrd.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$8,491.92', '171', '1.16%', 'Rooted', 'https://stay-rooted.com/', '3'),
        ('n/a', 'No', 'USA', 'Yes', '$8,636.40', '314', '3.38%', 'Shop Premium Outlet', 'https://shoppremiumoutlets.com/', '0'),
        ('No', 'No', 'USA', 'No', '$16,253.61', '246', '12.46%', 'Dicks Sporting Goods', 'https://www.dickssportinggoods.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$7,984.70', '111', '0.00%', 'Slam Jam', 'https://us.slamjam.com/', '1'),
        ('n/a', 'No', 'EU', 'Yes', '$7,546.00', '94', '0.00%', 'AFEW Store', 'https://en.afew-store.com/', '0'),
        ('No', 'No', 'USA', 'No', '$7,133.29', '78', '0.00%', 'SNS', 'https://www.sneakersnstuff.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$16,761.24', '306', '33.48%', 'kith', 'https://kith.com/', '0'),
        ('No', 'No', 'USA', 'Yes', '$14,314.69', '209', '40.46%', 'Shoe Palace', 'https://www.shoepalace.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$6,121.58', '132', '5.04%', 'ShopWSS', 'https://www.shopwss.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$5,679.18', '65', '0.00%', 'SoleFly', 'https://www.solefly.com/', '1'),
        ('Yes', 'No', 'USA', 'Yes', '$5,671.73', '46', '0.00%', 'Tops and Bottoms USA', 'https://www.topsandbottomsusa.com/', '0'),
        ('No', 'No', 'USA', 'Yes', '$4,320.45', '52', '0.00%', 'Private Sneakers', 'https://www.privatesneakers.com/', '1'),
        ('n/a', 'No', 'USA', 'No', '$4,315.00', '46', '41.77%', 'Fitness Sports', 'https://shop.fitnesssports.com/', '2'),
        ('n/a', 'No', 'USA', 'Yes', '$4,257.00', '45', '4.26%', 'Bodega', 'https://bdgastore.com/', '2'),
        ('No', 'No', 'USA', 'Yes', '$4,198.50', '38', '28.30%', 'UP NYC', 'https://upnycstore.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$3,381.44', '33', '13.16%', 'Austin''s Shoes', 'https://www.austinsshoes.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$3,368.40', '32', '8.57%', 'High Country Outfitters', 'https://highcountryoutfitters.com/', '0'),
        ('No', 'No', 'USA', 'No', '$4,092.47', '66', '44.54%', 'JD Sports', 'https://www.jdsports.com/', '2'),
        ('n/a', 'No', 'USA', 'No', '$2,997.50', '31', '0.00%', 'HBX', 'https://hbx.com/', '2'),
        ('n/a', 'No', 'USA', 'No', '$2,938.00', '42', '0.00%', 'Bait', 'https://www.baitme.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$2,786.59', '31', '60.76%', 'Running Warehouse', 'https://www.runningwarehouse.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$2,752.09', '32', '11.11%', 'Kicks Lounge', 'https://www.kickslounge.com/', '0'),
        ('n/a', 'No', 'EU', 'No', '$2,480.73', '63', '0.00%', 'BSTN', 'https://www.bstn.com/', '0'),
        ('Yes', 'No', 'USA', 'No', '$2,461.00', '27', '20.59%', 'Tennis Express', 'https://www.tennisexpress.com/', '2'),
        ('n/a', 'No', 'USA', 'Yes', '$2,384.36', '40', '0.00%', 'Notre', 'https://www.notre-shop.com/', '1'),
        ('n/a', 'No', '', '', '$1,876.90', '39', '11.36%', 'Xhibition', 'https://www.xhibition.co/', '3'),
        ('n/a', 'No', 'USA', 'Yes', '$2,089.64', '26', '3.70%', 'Totem Brand', 'https://totemshop.com/', '0'),
        ('n/a', 'No', 'CANADA', 'No', '$1,507.00', '23', '0.00%', 'SSENSE', 'https://www.ssense.com/en-us', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$1,417.60', '14', '0.00%', 'Sole Classics', 'https://www.soleclassics.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$1,371.15', '34', '35.85%', 'Rule of Next', 'https://www.ruleofnext.com/', '5'),
        ('Yes', 'No', 'USA', 'Yes', '$1,278.30', '17', '0.00%', 'HIT Pro Shop', 'https://hitproshop.shop/', '0'),
        ('n/a', 'No', 'USA', 'No', '$1,273.81', '21', '27.59%', 'Farfetch', 'https://www.farfetch.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$1,241.00', '13', '45.83%', 'Wish ATL', 'https://wishatl.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$1,166.27', '16', '5.88%', 'Soleplay ATL', 'https://www.soleplayatl.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$1,143.60', '12', '7.69%', 'The Loop Running Supply Co.', 'https://thelooprunning.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$1,128.20', '12', '36.84%', 'Grivet Outdoors', 'https://www.grivetoutdoors.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$1,047.20', '11', '0.00%', 'Social Status PGH', 'https://www.socialstatuspgh.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$1,020.00', '12', '66.67%', 'On', 'https://www.on.com/en-us/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$999.50', '10', '33.33%', 'Sole Provisions', 'https://www.soleprovisions.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$966.87', '13', '0.00%', 'The Backpacker', 'backpackeroutdoors.com', '1'),
        ('n/a', 'No', 'USA', 'No', '$961.80', '11', '0.00%', 'LN-CC', 'https://www.ln-cc.com/', '4'),
        ('n/a', 'No', '', '', '$899.91', '10', '0.00%', 'Just Golf Stuff', 'justgolfstuff.com', '0'),
        ('n/a', 'No', 'USA', 'No', '$842.00', '9', '64.00%', 'MR PORTER', 'https://www.mrporter.com/', '0'),
        ('No', 'No', 'USA', 'No', '$831.37', '8', '0.00%', 'Nordstrom', 'https://www.nordstrom.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$813.86', '8', '11.11%', 'Bloomingdale''s', 'https://www.bloomingdales.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$2,853.41', '33', '37.74%', 'Fit 2 Run', 'https://www.fit2run.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$791.64', '8', '0.00%', 'Brown''s Shoe Fit Co', 'https://brownsshoefitco.com/', '0'),
        ('n/a', 'No', 'EU', 'No', '$785.00', '20', '0.00%', 'LVR', 'https://www.luisaviaroma.com/', '0'),
        ('n/a', 'No', 'USA', '', '$784.00', '10', '0.00%', 'SVRN', 'https://www.svrn.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$771.00', '12', '0.00%', 'Packer Shoes', 'https://packershoes.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$909.25', '15', '6.25%', 'Manor PHX', 'https://www.manorphx.com/', '0'),
        ('n/a', 'No', 'CANADA', 'Yes', '$697.08', '7', '0.00%', 'Altitude Sports', 'https://www.altitude-sports.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$679.00', '7', '12.50%', 'Danform Shoes', 'https://www.danformshoesvt.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$641.91', '15', '0.00%', 'The Better Generation', 'https://thebettergeneration.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$635.00', '11', '8.33%', 'Reynold and Sons', 'https://www.reynoldsandsons.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$616.25', '7', '63.16%', 'Puritan Cape Cod', 'https://puritancapecod.com/', '0'),
        ('n/a', 'No', 'USA', '', '$611.99', '7', '0.00%', 'Tip Top Shoes', 'https://tiptopshoes.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$583.98', '10', '0.00%', 'GBNY', 'https://gbny.com/', '2'),
        ('n/a', 'No', 'USA', 'Yes', '$550.72', '6', '0.00%', 'Hola Bird Sports', 'https://www.holabirdsports.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$539.95', '6', '0.00%', 'Neptune Mountaineering', 'https://neptunemountaineering.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$499.75', '5', '16.67%', 'Marathon Sports', 'https://shop.marathonsports.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$499.41', '5', '0.00%', 'Athletic Annex', 'https://athleticannex.com', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$492.58', '5', '54.55%', 'Comfort One Shoes', 'https://comfortoneshoes.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$484.94', '6', '14.29%', 'Hornor and Harrison', 'https://hornorharrison.com/', '0'),
        ('n/a', 'No', '', '', '$472.22', '6', '0.00%', 'Grinmore', 'https://www.grinmorestore.com/', '0'),
        ('n/a', 'No', '', '', '$461.96', '5', '0.00%', 'Geiger''s', 'https://www.shopgeigers.com/', '0'),
        ('n/a', 'No', 'USA', '', '$445.20', '4', '0.00%', 'SoleStop', 'https://www.solestop.com/', '0'),
        ('No', 'Yes', 'USA', 'No', '$437.72', '6', '84.62%', 'REI Co-op', '', '0'),
        ('n/a', 'N/A', 'USA', '', '$1,143.00', '17', '0.00%', 'Lapstone and Hammer', 'https://www.lapstoneandhammer.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$397.50', '4', '78.95%', 'Runners Plus', 'https://www.runnersplus.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$377.82', '4', '60.00%', 'Lebos', 'https://www.lebos.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$356.35', '3', '0.00%', 'Kings', 'https://www.shopatkings.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$450.40', '8', '0.00%', 'Premier', 'https://thepremierstore.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$283.80', '4', '0.00%', 'Centre TX', 'https://www.centretx.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$280.43', '3', '25.00%', 'Yarid''s', 'https://yarids.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$270.00', '3', '0.00%', 'Soul Cycle', 'https://www.soul-cycle.com/', '0'),
        ('n/a', 'No', 'EU', 'No', '$259.00', '4', '0.00%', 'Yoox', 'https://www.yoox.com/', '1'),
        ('No', 'No', 'USA', 'Yes', '$240.00', '2', '0.00%', 'Extrabutter NY', 'https://extrabutterny.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$209.97', '3', '0.00%', 'Carbon 38', 'https://carbon38.com/', '0'),
        ('n/a', 'No', '', '', '$209.76', '2', '0.00%', 'Ski Rack', '', '0'),
        ('n/a', 'No', 'USA', 'No', '$198.00', '2', '0.00%', 'Ogden Run Co.', 'https://shop.ogdenrunco.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$195.94', '2', '0.00%', 'Peltz Shoes', 'https://www.peltzshoes.com/', '3'),
        ('n/a', 'No', 'USA', 'Yes', '$184.50', '2', '0.00%', 'Undefeated', 'https://undefeated.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$175.84', '2', '0.00%', 'Gary''s', 'https://garysonline.com/', '0'),
        ('Yes', 'No', 'USA', 'No', '$169.15', '5', '0.00%', 'Backcountry', 'https://www.backcountry.com/', '2'),
        ('n/a', 'No', 'EU', 'No', '$155.13', '2', '0.00%', 'SOTF', 'https://www.sotf.com/en/login.php', '0'),
        ('', 'No', 'USA', 'No', '$217.88', '6', '0.00%', 'Tilly''s', 'https://www.tillys.com/', ''),
        ('n/a', 'No', 'USA', '', '$118.50', '1', '0.00%', 'Silver Creek Outfitters', 'https://shop.silver-creek.com/', '0'),
        ('n/a', 'No', '', '', '$111.99', '1', '0.00%', 'Dardano''s', '', '0'),
        ('n/a', 'No', 'EU', 'No', '$110.00', '1', '0.00%', 'Matches Fashion', 'https://www.matchesfashion.com/', '0'),
        ('No', 'No', 'USA', 'No', '$109.33', '2', '0.00%', 'Academy Sports', 'https://www.academy.com/', '0'),
        ('n/a', 'No', '', '', '$100.78', '1', '0.00%', 'Next Adventure', 'https://nextadventure.net/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$98.00', '1', '0.00%', 'Kicking IT', 'https://kickingit.com/', '0'),
        ('n/a', 'No', 'USA', 'Yes', '$97.99', '1', '75.00%', 'La Favorita', 'https://lafavorita.com/', '1'),
        ('n/a', 'No', 'USA', 'Yes', '$91.47', '1', '0.00%', 'Idaho Mountain Touring', 'https://www.idahomountaintouring.com/', '0'),
        ('n/a', 'Yes', 'USA', 'Yes', '$91.00', '1', '88.89%', 'Fleet Feet', 'https://www.fleetfeet.com/', '0'),
        ('n/a', 'Yes', 'USA', 'No', '$89.99', '1', '92.86%', 'Peter Glenn Ski & Sports', 'https://www.peterglenn.com/', '0'),
        ('n/a', 'No', 'USA', 'No', '$65.50', '1', '0.00%', 'LVRG + Capitalist', 'https://lvrg-capitalist.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Half-Moon Outfitters', 'https://www.halfmoonoutfitters.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Out There Outfitters', 'https://outthereoutfitters.com/', '0'),
        ('No', 'Yes', 'USA', 'No', '$0.00', '5', '0.00%', 'Shiekh', 'https://www.shiekh.com/', '1'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Zappos', 'zappos.com', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '8', '0.00%', 'Foster', 'https://shopfoster.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Earth Walk Shoes', '', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Bivouac', 'https://www.bivouacannarbor.com//', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', '18montrose', 'https://www.18montrose.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'A Ma Maniere', 'https://www.a-ma-maniere.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Addict Miami', 'https://www.addictmiami.com/', '1'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Al''s', 'https://www.als.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Alabama Outdoors', 'https://alabamaoutdoors.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'All Shoes Nation', 'https://allshoesnation.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'All Sole', 'https://www.allsole.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'All The Right', 'https://alltheright.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Allez Outdoor', 'https://allezoutdoor.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Anthropologie', 'https://www.anthropologie.com', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Antonioli', 'https://antonioli.eu/en-us', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'AppOutdoors.com', 'https://www.appoutdoors.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Arrive', '', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Arts and Rec', 'https://artsandrecstore.com/', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Asphaltgold', 'https://www.asphaltgold.com/en/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'August', 'https://august-shop.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Back door', 'https://back-door.it/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Barebones Living', 'https://barebonesliving.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Berg''s Ski and Snowboard Shop', 'https://www.bergsskishop.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'bergfreunde', 'https://www.bergfreunde.eu/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Bike24', 'https://www.bike24.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Black Diamond Equipment', 'https://www.blackdiamondequipment.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Black Sheep Skate Shop', 'https://blacksheepskateshop.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Bob''s Stores', 'http://www.bobstores.com/', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Bouncewear', 'https://bouncewear.com', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Bows and Arrows Berkley', 'https://bowsandarrowsberkeley.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'BRoadout', 'https://www.broadout.com/', '0'),
        ('n/a', 'N/A', 'CANADA', 'No', '$0.00', '0', '-', 'Browns Shoes', 'https://www.brownsshoes.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Budget Golf', 'https://www.budgetgolf.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Burn Rubber', 'https://burnrubbersneakers.com/', '0'),
        ('Yes', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Camp Saver', 'https://www.campsaver.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Cascadia Vehicle Tents', 'https://cascadiatents.com/', '0'),
        ('n/a', 'N/A', 'AU', 'No', '$0.00', '0', '-', 'Cettire', 'https://www.cettire.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Christy Sports', 'https://www.christysports.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Chrome Industries', 'https://www.chromeindustries.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'City Jeans', 'https://cityjeans.com/', '0'),
        ('No', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Civilized Nation', 'https://civilizednationshop.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Commonwealth Running Company', 'https://commonwealthrunning.com/', '0'),
        ('n/a', 'N/A', 'CANADA', 'Yes', '$0.00', '0', '-', 'Courtside Sneakers', 'https://www.courtsidesneakers.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Creme321', 'https://creme321.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Daniel Footwear', 'https://www.danielfootwear.com/', '1'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Data Vision', 'https://datavision.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Decathlon', 'https://www.decathlon.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Denim Exchange USA', 'https://denimexchangeusa.com/', '1'),
        ('Yes', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Dick Pond Athletics', 'https://www.dickpondathletics.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'DNA Footwear', 'https://www.dnafootwear.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Dodds Shoe Co', 'https://www.doddsshoe.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'DSMNY', 'https://shop-us.doverstreetmarket.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Eames NW', 'https://eamesnw.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Envirolog', 'https://envirolog.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Equipe Sport', 'https://www.lequipe.fr/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Everest', 'https://www.everestoutdoor.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Evo', 'https://www.evo.com/', '1'),
        ('n/a', 'N/A', 'CANADA', 'Yes', '$0.00', '0', '-', 'Exclusity', 'https://shop.exclucitylife.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Flannels', 'https://www.flannels.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Fogatti', 'https://fogatti.com/', '0'),
        ('n/a', 'N/A', 'EU', '', '$0.00', '0', '-', 'Foot District', 'https://footdistrict.com/en', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Foot Patrol', 'https://www.footpatrol.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Footprint USA', 'https://footprintusa.co/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Free People', 'https://www.freepeople.com/shoes/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Front Runner Athletics', 'https://frontrunnerathletics.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Front Runners LA', 'https://frontrunnersla.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'FRWD', 'https://www.fwrd.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Gathr Outdoors', 'https://www.gathroutdoors.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Gazelle Sports', 'https://gazellesports.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Gearhead Outfitters', 'https://gearheadoutfitters.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Gerber Gear', 'https://www.gerbergear.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'GetSkiTickets', 'https://getskitickets.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Getz''s', 'https://www.getzs.com/customer/home.php', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'GILT', 'https://www.gilt.com/', '0'),
        ('', '', '', '', '', '', '', 'Rue La La', 'https://www.ruelala.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Got Your Gear', 'https://gotyourgear.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Hagan Ski Mountaineering', 'https://www.haganskimountaineering.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Hanig''s', 'https://www.hanigs.com/', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Harrods', 'https://www.harrods.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Hays County Outfitters', 'https://www.hayscooutfitters.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Heartbreak', '', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'HHV', 'https://www.hhv.de/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'High Snobiety', 'https://www.highsnobiety.com/', '1'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Hirshleifers', 'https://hirshleifers.com/', '0'),
        ('n/a', 'N/A', 'CANADA', 'No', '$0.00', '0', '-', 'Holt Renfrew ', 'https://www.holtrenfrew.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Holy Pop Store', 'https://www.holypopstore.com/en/footwear-men', '3'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Huckberry', 'https://huckberry.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Hush Life Botique', 'https://hushlifeboutique.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Island Trends', 'https://islandtrends.com/', '1'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Jack''s Surfboards', 'https://jackssurfboards.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Jans', 'https://www.jans.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'JR286', 'https://www.jr286.com/contact-us/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Juice Store USA', 'https://juicestoreusa.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Jules B', 'https://www.julesb.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Karen Walker', 'https://www.karenwalker.com/', '1'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Karma Loop', 'https://www.karmaloop.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Kaufman Shoes', 'https://www.kaufmanshoesonline.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Kelty', 'https://www.kelty.com/', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'KICKZ', 'https://www.kickz.com/en/l/jordan/retros/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Klymit', 'https://klymit.gathroutdoors.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Kogalla', 'https://kogalla.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Lace Up NYC', 'https://laceupnyc.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Leaders 1354', 'https://www.ldrs1354.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Lenny''s Shoe & Apparel', 'https://lennyshoe.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Liftopia', 'https://www.liftopia.com/', '0'),
        ('n/a', 'N/A', 'CANADA', 'Yes', '$0.00', '0', '-', 'Livestock', 'https://www.deadstock.ca/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'LONG BEACH SKATE CO', 'https://lbskate.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Luke''s Locker', 'https://lukeslocker.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Luno', 'https://lunolife.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'M. Dumas & Sons', 'https://mdumasandsons.com/', '1'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Maha', 'https://www.maha-amsterdam.com/', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Maison Threads', 'https://www.maisonthreads.com/', '1'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Major DC', 'https://www.majordc.com', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Metro Fusion', 'https://www.metrofusion.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Millenium Shoes', 'https://millenniumshoes.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Moda3', 'https://www.moda3.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Modesens', 'https://modesens.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Moon Fabrications', 'https://moonfab.com/', '0'),
        ('YES', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Moosejaw', 'https://www.moosejaw.com/', '0'),
        ('No', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Mountain High Outfitters', 'https://mountainhighoutfitters.com/', '2'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'MyTheresa', 'https://www.mytheresa.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Naked', 'https://www.nakedcph.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Nomadica Outfitters', 'https://nomadicaoutfitters.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Northland USA', 'https://www.northland-usa.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'OMCgear', 'https://omcgear.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Oneness', 'https://www.onenessboutique.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Orchard', 'https://orchardshop.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Osprey Packs', '', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'outdoor DIVAS', '', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Outdoor Gear Exchange', '', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Outdoor Master', '', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Outdoor Research', '', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Outdoorplay', '', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Pacers Running', 'https://runpacers.com/', '1'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Pacsun', 'https://www.pacsun.com/', '1'),
        ('n/a', 'N/A', 'UK', 'Yes', '$0.00', '0', '-', 'Pam Pam', 'https://pampamlondon.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Phenom Global', 'https://phenomglobal.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Polar Bear Coolers', '', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Poppy Sports', '', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Premium Goods', 'https://premiumgoods.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Proper', 'https://properlbc.com/', '1'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Public Lands', 'https://www.publiclands.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Puetz Golf', 'https://www.puetzgolf.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Puffer Reds', 'Pufferreds.com', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Ravean', '', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Reeds', 'https://reedsms.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Renarts', 'https://renarts.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Republic of Durable Goods', '', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Ridge Merino', '', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Road Runner Sports', '', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Robertson Madison', 'https://www.robertsonmadison.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Rock City Kicks', 'https://rockcitykicks.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Rossignol', '', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'RSVP Gallery', 'https://rsvpgallery.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Rukus Shoes', 'https://www.rukus103.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Run Appeal', 'https://www.runappeal.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Run Colors', 'https://runcolors.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Running Room', 'https://us.shop.runningroom.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'RUX', '', '0'),
        ('n/a', 'N/A', 'CANADA', 'No', '$0.00', '0', '-', 'Sam Tabak', 'https://www.samtabak.com/us/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Scheels', 'https://www.scheels.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Selfridges', 'https://www.selfridges.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'Seliga Shoes', 'seligashoes.com', '0'),
        ('n/a', 'N/A', 'SA', 'No', '$0.00', '0', '-', 'Shelflife', 'https://www.shelflife.co.za/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Shinzo Paris', 'https://www.shinzo.paris/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Shoe Gallery Miami', 'https://shoegallerymiami.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Shop Nice Kicks', 'https://shopnicekicks.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Shoptiques', 'https://shoptiques.com/', '2'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Sierra', 'https://www.sierra.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Sigma Sports', 'https://www.sigmasports.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Size Co', 'https://www.size.co.uk/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Skis.com', '', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Skyros Running', 'https://skyrosrunning.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Slumberjack', '', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Sneaker Junkies', 'https://sneakerjunkiesusa.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Sneaker Room', 'https://www.snkrroom.com/', '0'),
        ('n/a', 'N/A', 'CANADA', 'Yes', '$0.00', '0', '-', 'Sneakerbox', 'https://sneakerboxshop.ca/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Soccer.com', 'https://www.soccer.com/', '1'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Sole Desire', 'https://shopsoledesire.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Solebox', 'https://www.solebox.com/', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Solestory', 'https://thesolestory.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Somewhere Official', 'https://somewhereofficial.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Soul Poles', '', '0'),
        ('n/a', 'N/A', 'CANADA', 'No', '$0.00', '0', '-', 'SportChek', 'https://www.sportchek.ca/', '0'),
        ('n/a', 'N/A', 'CANADA', 'No', '$0.00', '0', '-', 'Sporting Life', 'https://www.sportinglife.ca/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Sports Basement', 'https://shop.sportsbasement.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Stan''s Footwear', 'https://www.stansfootwear.com/', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Stash1250', 'https://www.stash1250.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'StashedSF', 'https://stashedsf.com/', '0'),
        ('Yes', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Steep and Cheap', 'https://www.steepandcheap.com/', '0'),
        ('n/a', 'N/A', 'USA', 'yes', '$0.00', '0', '-', 'STNDRD', 'https://stndrdnola.com/', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Stress95', 'https://stress95.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Suburban Shoes', 'https://suburbanshoes.com/', '0'),
        ('No', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'Sun and Ski', 'https://www.sunandski.com/', '0'),
        ('n/a', 'N/A', 'EU', 'Yes', '$0.00', '0', '-', 'Sunika Sneakers', 'https://www.sunikasneakers.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Super Runners Shop', 'https://superrunnersshop.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'SVD', 'https://www.sivasdescalzo.com/us', '0'),
        ('Yes', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Takout NY', 'https://takoutny.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'TC Running Co', 'https://tcrunningco.com/', '0'),
        ('n/a', 'N/A', 'AU', '', '$0.00', '0', '-', 'The Athlete''s Foot', 'https://www.theathletesfoot.com.au/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'The Clymb', 'https://theclymb.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'The Dark Side Initiative', 'https://www.thedarksideinitiative.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'The Heel', 'https://theheel.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'The Marathon Sports', 'https://shop.marathonsports.com/', '0'),
        ('n/a', 'N/A', 'UK', '', '$0.00', '0', '-', 'The Sports Edit', 'https://us.thesportsedit.com/', '0'),
        ('No', 'N/A', 'USA', '', '$0.00', '0', '-', 'Trendy Golf', 'https://trendygolfusa.com/', '0'),
        ('n/a', 'N/A', 'EU', 'No', '$0.00', '0', '-', 'Tres Bien', 'https://tres-bien.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'Trophy Room', 'https://www.trophyroomstore.com/', '0'),
        ('n/a', 'N/A', 'EU', '', '$0.00', '0', '-', 'Varuste', 'https://varuste.net/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Veri Shop', 'https://www.verishop.com/', '0'),
        ('n/a', 'N/A', 'EU', '', '$0.00', '0', '-', 'Voo Berlin', 'https://www.vooberlin.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'Waco Running Company', 'https://wacorunningcompany.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'Water + OAK', 'https://waterandoakoutdoor.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'Whole Earth Provision', 'https://www.wholeearthprovision.com/', '1'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Wildhorn Outfitters', '', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'Woodstack', 'https://www.woodstack.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'WUBEN', '', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'ZERO BREEZE Tech Inc', '', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'Zumiez', 'https://www.zumiez.com/', '0'),
        ('n/a', 'N/A', 'USA', '', '$0.00', '0', '-', 'Saxon Shoes', 'https://saxonshoes.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Good Miles Running', '', '0'),
        ('n/a', 'N/A', 'USA', 'No', '$0.00', '0', '-', 'T3 Endurance', 'https://www.t3endurancesports.com/', '0'),
        ('n/a', 'Yes', '', '', '$0.00', '0', '-', 'Elkmont Trading Company', 'https://elkmonttradingcompany.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'City Gear', 'https://www.citygear.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Kohls', 'https://www.kohls.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'ShoeCarnival', 'https://www.shoecarnival.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'ShoeShowMega', 'https://www.shoeshowmega.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'DSW', 'https://www.dsw.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Macy''s', 'https://www.macys.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'RockRoomShoes', 'https://www.rackroomshoes.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Arvada Triathalon Company', 'https://arvadatri.com', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Shoebacca', 'https://www.shoebacca.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'OneBlockDown', 'https://oneblockdown.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'ShopAtKings', 'https://www.shopatkings.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'CRSVR', 'https://crsvr.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'PremiumGoods', 'https://premiumgoods.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Rukus', 'https://www.rukus103.com/', '0'),
        ('n/a', 'N/A', 'USA', 'Yes', '$0.00', '0', '-', 'NJ Skateshop', 'https://njskateshop.com/', '0'),
        ('n/a', 'N/A', '', '', '$0.00', '0', '-', 'Shop Sportive', 'https://shopsportive.com/', '0'),
        ('', '', 'USA', '', '$62.40', '1', '0.00%', 'Todd Snyder', 'https://www.toddsnyder.com/', '3'),
        ('', '', '', '', '$5,764.91', '109', '', 'Urban Outfitters', '', '0'),
        ('', '', '', '', '$0.00', '0', '', 'Saratoga Outdoors', 'https://saratogaoutdoors.com/', '0')
) AS data(wholesale_col, cancel_col, location_col, shopify_col, spend_col, qty_col, percent_col, name_col, link_col, coupons_col)
WHERE TRIM(name_col) != '' AND TRIM(name_col) IS NOT NULL
ON CONFLICT (name) DO UPDATE SET
    link = EXCLUDED.link,
    wholesale = EXCLUDED.wholesale,
    cancel_for_bulk = EXCLUDED.cancel_for_bulk,
    location = EXCLUDED.location,
    shopify = EXCLUDED.shopify,
    total_spend = EXCLUDED.total_spend,
    total_qty_of_items_ordered = EXCLUDED.total_qty_of_items_ordered,
    percent_of_cancelled_qty = EXCLUDED.percent_of_cancelled_qty,
    updated_at = CURRENT_TIMESTAMP;

-- Check the result
SELECT COUNT(*) as total_retailers FROM retailers;

