"""
Retailer registry — single source of truth for retailer capabilities.

Each retailer entry defines:
  - display_name: Human-readable name for Slack display
  - has_url_id: Whether unique_id_extractor.py supports this retailer's URLs
  - manual_id_note: Description of any manual/semi-manual unique ID process (or None)
  - has_order: Whether the parser has parse_email() for order confirmations
  - has_shipping: Whether the parser has parse_shipping_email()
  - has_cancellation: Whether the parser has parse_cancellation_email()
  - shipping_types: Which shipping types are tested ("full", "partial", or both)
  - cancellation_types: Which cancellation types are tested ("full", "partial", or both)
"""

RETAILERS: dict[str, dict] = {
    "footlocker": {
        "display_name": "FootLocker",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "champs": {
        "display_name": "Champs Sports",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "dicks": {
        "display_name": "Dick's",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "hibbett": {
        "display_name": "Hibbett",
        "has_url_id": False,
        "manual_id_note": "Amplience code extracted by Apps Script",
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "dtlr": {
        "display_name": "DTLR",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "shoepalace": {
        "display_name": "Shoe Palace",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "snipes": {
        "display_name": "Snipes",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "finishline": {
        "display_name": "Finish Line",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "jdsports": {
        "display_name": "JD Sports",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "shopsimon": {
        "display_name": "ShopSimon",
        "has_url_id": False,
        "manual_id_note": "Fabricated ID",
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "urban": {
        "display_name": "Urban Outfitters",
        "has_url_id": True,
        "manual_id_note": "Normalized slug + color code",
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full", "partial"],
        "cancellation_types": ["partial"],
    },
    "bloomingdales": {
        "display_name": "Bloomingdale's",
        "has_url_id": False,
        "manual_id_note": "3 separate ID systems; not feasible",
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "anthropologie": {
        "display_name": "Anthropologie",
        "has_url_id": True,
        "manual_id_note": "Slug only, no color",
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "nike": {
        "display_name": "Nike",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "carbon38": {
        "display_name": "Carbon38",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "gazelle": {
        "display_name": "Gazelle Sports",
        "has_url_id": False,
        "manual_id_note": "Shopify slug != email ID",
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "netaporter": {
        "display_name": "NET-A-PORTER",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "fit2run": {
        "display_name": "Fit2Run",
        "has_url_id": False,
        "manual_id_note": "Shopify slug != email ID",
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "sns": {
        "display_name": "SNS",
        "has_url_id": False,
        "manual_id_note": "Slug only, no email match",
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "adidas": {
        "display_name": "Adidas",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "concepts": {
        "display_name": "CNCPTS",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "sneaker": {
        "display_name": "Sneaker Politics",
        "has_url_id": False,
        "manual_id_note": "Shopify slug != email ID",
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "orleans": {
        "display_name": "Orleans Shoe Co",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": True,
        "shipping_types": [],
        "cancellation_types": ["partial"],
    },
    "revolve": {
        "display_name": "Revolve",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full", "partial"],
        "cancellation_types": ["partial"],
    },
    "asos": {
        "display_name": "ASOS",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": False,
        "shipping_types": ["full"],
        "cancellation_types": [],
    },
    "endclothing": {
        "display_name": "END Clothing",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": False,
        "shipping_types": ["full"],
        "cancellation_types": [],
    },
    "shopwss": {
        "display_name": "ShopWSS",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["full", "partial"],
    },
    "on": {
        "display_name": "On Running",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "als": {
        "display_name": "Al's Sporting Goods",
        "has_url_id": True,
        "manual_id_note": "Slack color reply workflow for composite ID",
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full", "partial"],
        "cancellation_types": ["partial"],
    },
    "sierra": {
        "display_name": "Sierra",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": False,
        "shipping_types": ["full"],
        "cancellation_types": [],
    },
    "nordstrom": {
        "display_name": "Nordstrom",
        "has_url_id": False,
        "manual_id_note": "URL ID != email ID",
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "sportsbasement": {
        "display_name": "Sports Basement",
        "has_url_id": False,
        "manual_id_note": "Completely unusable",
        "has_order": False,
        "has_shipping": False,
        "has_cancellation": False,
        "shipping_types": [],
        "cancellation_types": [],
    },
    "macys": {
        "display_name": "Macy's",
        "has_url_id": False,
        "manual_id_note": "Manual: user assigns image ID from email",
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["partial"],
    },
    "fwrd": {
        "display_name": "FWRD",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": True,
        "shipping_types": ["full"],
        "cancellation_types": ["full"],
    },
    "academy": {
        "display_name": "Academy Sports",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": False,
        "shipping_types": ["full"],
        "cancellation_types": [],
    },
    "scheels": {
        "display_name": "Scheels",
        "has_url_id": True,
        "manual_id_note": None,
        "has_order": True,
        "has_shipping": True,
        "has_cancellation": False,
        "shipping_types": ["full"],
        "cancellation_types": [],
    },
}


def get_all_retailer_ids() -> list[str]:
    """Return sorted list of all retailer IDs."""
    return sorted(RETAILERS.keys())


def get_retailer(retailer_id: str) -> dict | None:
    """Get retailer config by ID."""
    return RETAILERS.get(retailer_id)
